### ISSUE TITLE
Deploy Advisor

### ISSUE THREAD

**Issue by tumido** [AICoE/seraph#18]
App Interface:
https://visual-app-interface.devshift.net/services#/services/insights/advisor/app.yml

Private repos:
https://quay.io/repository/cloudservices/advisor-backend
https://quay.io/repository/cloudservices/content-server
https://quay.io/repository/cloudservices/insights-advisor-api
https://quay.io/repository/cloudservices/insights-advisor-db
https://quay.io/repository/cloudservices/insights-advisor-service
https://github.com/RedHatInsights/insights-advisor-api
https://github.com/RedHatInsights/insights-advisor-service (archive)
https://github.com/RedHatInsights/inventory-syndication
https://gitlab.cee.redhat.com/insights-platform/advisor-backend

**Comment by schwesig** [comment]
seraph is currently on hold
closing issues to clean up until this will be focussed again
/close
