### ISSUE TITLE
Opensource Advisor

### ISSUE THREAD

**Issue by tumido** [AICoE/seraph#19]
In order to deploy Advisor we need to have the undelying codebase open sourced first. Advisor repositories are private as well as their container images. This effectively blocks us from learning about the configuration, their dev/ci manifests and deploying it.

These repos needs to become available to us:
https://quay.io/repository/cloudservices/advisor-backend
https://quay.io/repository/cloudservices/content-server
https://quay.io/repository/cloudservices/insights-advisor-api
https://quay.io/repository/cloudservices/insights-advisor-db
https://quay.io/repository/cloudservices/insights-advisor-service
https://github.com/RedHatInsights/insights-advisor-api
https://github.com/RedHatInsights/insights-advisor-service (not needed probably, since it's an archive already)
https://github.com/RedHatInsights/inventory-syndication
https://gitlab.cee.redhat.com/insights-platform/advisor-backend

**Comment by tumido** [comment]
Hey @dkuc , sorry for the delay on this.. https://gitlab.cee.redhat.com/insights-platform/advisor-backend requires VPN since gitlab.cee.redhat.com is on RH internal network.

**Comment by dkuc** [comment]
Got it,  I didn't understand the goals of this project at the time.

**Comment by schwesig** [comment]
seraph is currently on hold
closing issues to clean up until this will be focussed again
/close
