### ISSUE TITLE
[EPIC] Seraph MVP progress tracking

### ISSUE THREAD

**Issue by tumido** [AICoE/seraph#9]
Deliver a MVP of Seraph that can ingest client payloads and process them.

- [x] #7 
- [x] #3 
- [x] #8 
- [ ] #1 
- [x] #2 
- [x] ~#4~ 
- [ ] #5 
- [ ] #6 
- [x] #20

Acceptance criteria:
- Client can send a payload to an API endpoint
- Payload shows in Host based inventory
- A minimal rule (insights) engine checks on the payload

Tracking project: https://github.com/orgs/AICoE/projects/8

**Comment by tumido** [comment]
Initial namespaces are deployed, Kafka is also deployed along with necessary topics for ingress and storage broker. Right now I'm deploying both of those components since it proved me that both are essential and are required to work together.

**Comment by schwesig** [comment]
seraph is currently on hold
closing issues to clean up until this will be focussed again
/close
